### ISSUE TITLE
Keywords that contain punctuation and special characters lead to an error

### ISSUE THREAD

**Issue by JuleZR** [JuleZR/Vigenere-Text-Encryptor#1]
**Keywords that contain punctuation and special characters lead to an error**

> Traceback (most recent call last):
>   File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
>     return self.func(*args)
>   File "e:\Developement\Projects\Python-Developement\Vigenère Incryptor\main.py", line 58, in encrypt_btn
>     enc.cipher = enc.encrypt()
>   File "e:\Developement\Projects\Python-Developement\Vigenère Incryptor\vigenere.py", line 88, in encrypt
>     cipher_letter = encrypt_letter(character, longer_key[counter])
>   File "e:\Developement\Projects\Python-Developement\Vigenère Incryptor\vigenere.py", line 73, in encrypt_letter
>     if (index + cipher) > 25:
> TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by JuleZR** [comment]
### Special characters are now encrypted as well
